package:
    name: elements
    version: "5.10"

source:
    git_rev: 5.10
    git_url: https://github.com/astrorama/Elements.git

build:
    number: 7
    run_exports:
        - {{ pin_subpackage('elements', max_pin='x.x.x') }}

test:
    commands:
        - $PREFIX/bin/python `which AddElementsModule` --version

requirements:
    build:
        - cmake >=3.0
        - make
        - {{ compiler('cxx') }}
    host:
        - boost-cpp ==1.70
        - log4cpp
        - python
        - pytest
        - cython
    run:
        - boost-cpp ==1.70
        - {{ pin_compatible('log4cpp') }}
        - {{ pin_compatible('python', min_pin='x.x', max_pin='x.x') }}
        - pytest

about:
    home: https://github.com/astrorama/Elements.git
    license: LGPL
    summary: Elements is a C++/Python build framework. It helps to organize the software into modules which are gathered into projects.

