package:
    name: elements
    version: "5.8"

source:
    git_rev: 5.8
    git_url: https://github.com/astrorama/Elements.git

build:
    number: 5

test:
    commands:
        - $PREFIX/bin/python `which AddElementsModule` --version

requirements:
    build:
        - cmake >=3.0
        - make
        - {{ compiler('cxx') }}
    host:
        - boost-cpp ==1.70
        - log4cpp
        - python
        - pytest
        - cython
    run:
        - boost-cpp ==1.70
        - log4cpp
        - python
        - pytest

about:
    home: https://github.com/astrorama/Elements.git
    license: LGPL
    summary: Elements is a C++/Python build framework. It helps to organize the software into modules which are gathered into projects.

